# Generated by Django 3.0.7 on 2020-06-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200621_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImg',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
