# Generated by Django 3.0.7 on 2020-06-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200621_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImg',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to=''),
        ),
    ]
