# Generated by Django 3.0.7 on 2020-06-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200622_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImg',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
