# Generated by Django 3.0.7 on 2020-06-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200617_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
